apiVersion: skaffold/v1beta11
kind: Config
deploy:
  helm:
    releases:
      - name: bookinfo
        wait: true
        chartPath: .
        setValueTemplates:
          istioDomain: "{{.ISTIO_DOMAIN}}"
