apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  metadata:
  name: reviews-v1
  labels:
    chart: {{ template "bookinfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.reviews.replicas }}
  selector:
    matchLabels:
      app: reviews
      release: {{ .Release.Name }}
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        release: {{ .Release.Name }}
        version: v1
    spec:
      containers:
      - name: reviews
        image: {{ .Values.reviews.image.v1 }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
